// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobin.CoreProject.Data;

namespace Mobin.CoreProject.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181008093111_LeafMigration")]
    partial class LeafMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mobin.CoreProject.Core.Entities.Forest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Forest");
                });

            modelBuilder.Entity("Mobin.CoreProject.Core.Entities.Leaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ForestId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ForestId");

                    b.ToTable("Leaf");
                });

            modelBuilder.Entity("Mobin.CoreProject.Core.Entities.Leaf", b =>
                {
                    b.HasOne("Mobin.CoreProject.Core.Entities.Forest", "Forest")
                        .WithMany("Leafs")
                        .HasForeignKey("ForestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
